### ISSUE TITLE
Auto theme broken on iOS light mode

### ISSUE THREAD

**Issue by OLEGSHA** [OLEGSHA/KenDB3#1]
On Safari on iOS, light nor dark theme is applied when the theme switch is set to auto and system theme is light.

Either light theme or dark theme must always be applied.
![CAE91375-E91E-45D4-A527-A180FB6A9452](https://github.com/OLEGSHA/KenDB3/assets/9787438/64f5834d-39d8-4624-99f3-e4702ab04ce4)

**Comment by Cezij** [comment]
It also dosent work when dark mode is enabled on Samsung Internet, but it works fine with light mode is applied on phone with manual buttons.
![Screenshot_20240416_195335_Samsung Internet](https://github.com/OLEGSHA/KenDB3/assets/107931729/97a8fb0f-0b48-441a-af4e-3ae4f3319e16)

**Comment by OLEGSHA** [comment]
> It also dosent work when dark mode is enabled on Samsung Internet, but it works fine with light mode is applied on phone with manual buttons.

This is probably an unrelated issue. I opened a separate issue for it: #5

**Comment by OLEGSHA** [comment]
In other news, `@media` queries in [`_themes.scss`](https://github.com/OLEGSHA/KenDB3/blob/main/javascript_pipeline/webpack_src/_themes.scss#L65-L77) are almost certainly to blame.
